### ISSUE TITLE
Error: undeclared identifier: 'Stat'

### ISSUE THREAD

**Issue by larky0071** [SolitudeSF/discord_rpc#1]
`PS C:\Users\Larky\Documents\GitHub\folx-nim> nimble run
  Verifying dependencies for folx@0.1.0
      Info: Dependency on discordrpc@any version already satisfied
  Verifying dependencies for discord_rpc@0.1.0
      Info: Dependency on uuids@any version already satisfied
  Verifying dependencies for uuids@0.1.11
      Info: Dependency on isaac@>= 0.1.3 already satisfied
  Verifying dependencies for isaac@0.1.3
      Info: Dependency on packedjson@any version already satisfied
  Verifying dependencies for packedjson@0.2.2
   Building folx/larky/test.exe using c backend
C:\Users\Larky\.nimble\pkgs\discord_rpc-0.1.0\discord_rpc.nim(261, 12) Error: undeclared identifier: 'Stat'
candidates (edit distance, scope distance); see '--spellSuggest': 
 (3, 2): 'Pan' [type declared in C:\Users\Larky\.nimble\pkgs\discord_rpc-0.1.0\discord_rpc.nim(72, 3)]
 (3, 2): 'net' [module declared in C:\Users\Larky\.nimble\pkgs\discord_rpc-0.1.0\discord_rpc.nim(1, 11)]
 (3, 4): 'JInt' [enumField declared in C:\Users\Larky\.nimble\pkgs\packedjson-0.2.2\packedjson.nim(62, 5)]
 (3, 4): 'NaN' [const declared in C:\Users\Larky\scoop\apps\nim\current\lib\system.nim(1529, 3)]
 (3, 4): 'Port' [type declared in C:\Users\Larky\scoop\apps\nim\current\lib\pure\nativesockets.nim(53, 3)]
 (3, 4): 'cas' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\system\atomics.nim(314, 8)]
 (3, 4): 'char' [type declared in C:\Users\Larky\scoop\apps\nim\current\lib\system.nim(33, 3)]
 (3, 4): 'cint' [type declared in C:\Users\Larky\scoop\apps\nim\current\lib\system.nim(1413, 3)]
 (3, 4): 'dial' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\pure\net.nim(1871, 6)]
 (3, 4): 'float' [type declared in C:\Users\Larky\scoop\apps\nim\current\lib\system.nim(26, 3)]
 (3, 4): 'get' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\pure\httpclient.nim(1178, 6)]
 (3, 4): 'get' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\pure\httpclient.nim(1178, 6)]
 (3, 4): 'get' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\pure\options.nim(182, 6)]
 (3, 4): 'get' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\pure\options.nim(197, 6)]
 (3, 4): 'get' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\pure\options.nim(209, 6)]
 (3, 4): 'head' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\pure\httpclient.nim(1171, 6)]
 (3, 4): 'head' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\pure\httpclient.nim(1171, 6)]
 (3, 4): 'int' [type declared in C:\Users\Larky\scoop\apps\nim\current\lib\system\basic_types.nim(2, 3)]
 (3, 4): 'lent' [type declared in C:\Users\Larky\scoop\apps\nim\current\lib\system.nim(307, 6)]
 (3, 4): 'map' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\pure\options.nim(225, 6)]
 (3, 4): 'map' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\pure\options.nim(244, 6)]
 (3, 4): 'max' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\system.nim(1571, 6)]
 (3, 4): 'max' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\system.nim(1573, 6)]
 (3, 4): 'max' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\system.nim(1577, 6)]
 (3, 4): 'max' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\system\comparisons.nim(224, 6)]
 (3, 4): 'max' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\system\comparisons.nim(226, 6)]
 (3, 4): 'max' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\system\comparisons.nim(228, 6)]
 (3, 4): 'max' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\system\comparisons.nim(230, 6)]
 (3, 4): 'max' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\system\comparisons.nim(232, 6)]
 (3, 4): 'max' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\system\comparisons.nim(243, 6)]
 (3, 4): 'not' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\system.nim(123, 6)]
 (3, 4): 'not' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\system\arithmetics.nim(166, 6)]
 (3, 4): 'not' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\system\arithmetics.nim(173, 6)]
 (3, 4): 'not' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\system\arithmetics.nim(174, 6)]       
 (3, 4): 'not' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\system\arithmetics.nim(175, 6)]       
 (3, 4): 'not' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\system\arithmetics.nim(176, 6)]       
 (3, 4): 'not' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\system\arithmetics.nim(323, 6)]       
 (3, 4): 'not' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\system\arithmetics.nim(325, 6)]       
 (3, 4): 'not' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\system\arithmetics.nim(326, 6)]       
 (3, 4): 'not' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\system\arithmetics.nim(327, 6)]
 (3, 4): 'not' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\system\arithmetics.nim(328, 6)]       
 (3, 4): 'not' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\system\basic_types.nim(45, 6)]        
 (3, 4): 'post' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\pure\httpclient.nim(1203, 6)]        
 (3, 4): 'post' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\pure\httpclient.nim(1203, 6)]        
 (3, 4): 'ptr' [type declared in C:\Users\Larky\scoop\apps\nim\current\lib\system.nim(42, 3)]
 (3, 4): 'put' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\pure\httpclient.nim(1217, 6)]
 (3, 4): 'put' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\pure\httpclient.nim(1217, 6)]
 (3, 4): 'quit' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\system.nim(1236, 8)]
 (3, 4): 'quit' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\system.nim(2476, 6)]
 (3, 4): 'set' [type declared in C:\Users\Larky\scoop\apps\nim\current\lib\system.nim(300, 3)]
 (3, 4): 'sort' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\pure\collections\tables.nim(1600, 6)]
 (3, 4): 'sort' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\pure\collections\tables.nim(2057, 6)]
 (3, 4): 'sort' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\pure\collections\tables.nim(2455, 6)]
 (3, 4): 'sort' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\pure\collections\tables.nim(2753, 6)]
 (3, 4): 'static' [type declared in C:\Users\Larky\scoop\apps\nim\current\lib\system.nim(222, 3)]
 (3, 4): 'swap' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\system.nim(1501, 6)]
 (3, 4): 'take' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\pure\collections\tables.nim(1076, 6)]
 (3, 4): 'take' [proc declared in C:\Users\Larky\scoop\apps\nim\current\lib\pure\collections\tables.nim(550, 6)] 
 (3, 4): 'uint' [type declared in C:\Users\Larky\scoop\apps\nim\current\lib\system\basic_types.nim(8, 3)]        
       Tip: 9 messages have been suppressed, use --verbose to show them.
     Error: Build failed for package: folx
        ... Execution failed with exit code 1
        ... Command: C:\Users\Larky\scoop\shims\nim.exe c --colors:on --noNimblePath -d:NimblePkgVersion=0.1.0 --path:C:\Users\Larky\.nimble\pkgs\discord_rpc-0.1.0 --path:C:\Users\Larky\.nimble\pkgs\uuids-0.1.11 --path:C:\Users\Larky\.nimble\pkgs\isaac-0.1.3 --path:C:\Users\Larky\.nimble\pkgs\packedjson-0.2.2 --hints:off -o:C:\Users\Larky\Documents\GitHub\folx-nim\larky\test.exe C:\Users\Larky\Documents\GitHub\folx-nim\src\larky\test.nim`

**Comment by SolitudeSF** [comment]
pushed a workaround
