### ISSUE TITLE
windows version

### ISSUE THREAD

**Issue by bung87** [SolitudeSF/discord_rpc#2]
am trying implement windows version, but it runs failed without stacktrace.
https://github.com/bung87/discord_rpc_puppy/tree/win

**Comment by SolitudeSF** [comment]
(un)fortunately, i dont have a windows system to test it on.

**Comment by bung87** [comment]
does it works fine on linux or macos ?

**Comment by SolitudeSF** [comment]
i use it on my linux machine every day.

**Comment by SolitudeSF** [comment]
if you isolate your windows work into separate pr, i would be happy to merge it.

**Comment by bung87** [comment]
![捕获3455465](https://github.com/SolitudeSF/discord_rpc/assets/2238294/9a2a5916-cf57-4108-b5c3-5106b9b84cac)
I can't confirm it works or not. it just show like that, even it runs without any error.
